/*
 * Boxcite.JS : the Boxcite-library for the frontend development
 *
 * @copyright mQuotient Solutions Limited
 * @developer Soumya Deb [DebWebDev]
 *
 */

(function(a){function b(a,b,c){this.data={};this.prefix="";if(typeof a!=="undefined"&&a.length>0){this.URL="http://"+a;if(typeof b!=="undefined"&&b.length>0){this.URL+=":"+b}if(typeof c!=="undefined"&&c.length>0){this.URL+=c}}else this.URL="http://localhost/xmlrpc/";this.getCookie=function(a){var b,c,d,e="";var f=document.cookie.split(";");var g=f.length;if(g>0&&f[0]!=""){for(b=0;b<g;b++){c=f[b].substr(0,f[b].indexOf("="));d=f[b].substr(f[b].indexOf("=")+1);c=c.replace(/^\s+|\s+$/g,"");if(c==a){e=unescape(d);return e}}}return e};this.setCookie=function(a,b,c,d,e){var f=new Date;f.setDate(f.getDate()+c);var g=escape(b)+(c==null?"":";expires="+f.toUTCString());g+=d==null?"":"; Domain="+escape(d);g+=e==null?"":"; Path="+escape(e);document.cookie=a+"="+g};this.delCookie=function(a){this.setCookie(a,"",1)};this.loginRequest=function(a,b){try{var c=new xmlrpc_client(this.URL);var d=typeof b==="undefined"?this.data:b;a=this.prefix+a;var e=c.mq_send(new xmlrpcmsg(a,new Array(xmlrpc_encode(d))));f=this.getCookie("sessionid");if(f==""){var f=e.cookies();this.setCookie("sessionid",f["sessionid"].value,f["sessionid"].expires)}e=xmlrpc_decode(e.value());return e}catch(g){g="Failed to initiate sending data - "+g;throw g}};this.logoutRequest=function(a){try{var b=new xmlrpc_client(this.URL);var c=this.getCookie("sessionid");var d={};if(c!=""){d.sessionID=c}a=this.prefix+a;var e=b.mq_send(new xmlrpcmsg(a,new Array(xmlrpc_encode(d))));e=xmlrpc_decode(e.value());this.delCookie("sessionid");return e}catch(f){f="Failed to initiate sending data - "+f;throw f}}}a.Boxcite=b})(window);var users=new Boxcite;users.prefix="mq.boxcite.user.";users.login=function(a){try{var b="login";response=this.loginRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};users.logout=function(a){try{var b="logout";response=this.logoutRequest(b);return response}catch(c){c="Error : "+c;throw c}}
