/*
 * Boxcite.JS : the Boxcite-library for the frontend development
 *
 * @copyright mQuotient Solutions Limited
 * @developer Soumya Deb [DebWebDev]
 *
 */

// Base Module //
(function(a){function b(a,b,c){this.data={};this.prefix="";if(typeof a!=="undefined"&&a.length>0){this.URL="http://"+a;if(typeof b!=="undefined"&&b.length>0){this.URL+=":"+b}if(typeof c!=="undefined"&&c.length>0){this.URL+=c}}else this.URL="http://sreejith.dyndns-home.com:10580/xmlrpc/";this.getCookie=function(a){var b,c,d,e="";var f=document.cookie.split(";");var g=f.length;if(g>0&&f[0]!=""){for(b=0;b<g;b++){c=f[b].substr(0,f[b].indexOf("="));d=f[b].substr(f[b].indexOf("=")+1);c=c.replace(/^\s+|\s+$/g,"");if(c==a){e=unescape(d);return e}}}return e};this.setCookie=function(a,b,c,d,e){var f=new Date;f.setDate(f.getDate()+c);var g=escape(b)+(c==null?"":";expires="+f.toUTCString());g+=d==null?"":"; Domain="+escape(d);g+=e==null?"":"; Path="+escape(e);document.cookie=a+"="+g};this.delCookie=function(a){this.setCookie(a,"",1)};this.loginRequest=function(a,b){try{var c=new xmlrpc_client(this.URL);var d=typeof b==="undefined"?this.data:b;a=this.prefix+a;var e=c.mq_send(new xmlrpcmsg(a,new Array(xmlrpc_encode(d))));g=this.getCookie("sessionid");var f=e.cookies();if(g==""&&f.sessionid){var g=f;this.setCookie("sessionid",g["sessionid"].value,g["sessionid"].expires)}e=xmlrpc_decode(e.value());return e}catch(h){h="Failed to communicate with the server.";throw h}};this.logoutRequest=function(a){try{var b=new xmlrpc_client(this.URL);var c=this.getCookie("sessionid");var d={};if(c!=""){d.sessionID=c}a=this.prefix+a;var e=b.mq_send(new xmlrpcmsg(a,new Array(xmlrpc_encode(d))));e=xmlrpc_decode(e.value());this.delCookie("sessionid");return e}catch(f){f="Failed to communicate with the server.";throw f}};this.sendRequest=function(a,b){try{var c=new xmlrpc_client(this.URL);var d=this.getCookie("sessionid");var e=b;if(d!=""){e.sessionID=d}a=this.prefix+a;var f=c.mq_send(new xmlrpcmsg(a,new Array(xmlrpc_encode(e))));f=xmlrpc_decode(f.value());return f}catch(g){g="Failed to communicate with the server.";throw g}}}a.Boxcite=b})(window)
// User Module //
var user=new Boxcite;user.prefix="mq.boxcite.user.";user.login=function(a){try{var b="login";response=this.loginRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};user.logout=function(a){try{var b="logout";response=this.logoutRequest(b);return response}catch(c){c="Error : "+c;throw c}};user.changePassword=function(a){try{var b="changePassword";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};user.resetPassword=function(a){try{var b="resetPassword";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};user.find=function(){try{var a="find";response=this.sendRequest(a,{});return response}catch(b){b="Error : "+b;throw b}};user.locations=function(){try{var a="locations";response=this.sendRequest(a,{});return response}catch(b){b="Error : "+b;throw b}}
// Contact Module //
var contact=new Boxcite;contact.prefix="mq.boxcite.contact.";contact.create=function(a){try{var b="createSingle";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.createFromFile=function(a){try{var b="createFromFile";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.readContact=function(a){try{var b="readContact";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.findContacts=function(a){try{var b="findContacts";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.findCategories=function(a){try{var b="findCategories";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.updateContact=function(a){try{var b="updateContact";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.updateCategories=function(a){try{var b="updateCategories";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.count=function(a){try{var b="count";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.countCategories=function(a){try{var b="countCategories";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.remove=function(a){try{var b="delete";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.export=function(a){try{var b="export";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};contact.getFields=function(a){try{var b="getFields";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}}
// Campaign Module //
var campaign=new Boxcite;campaign.prefix="mq.boxcite.campaign.";campaign.create=function(a){try{var b="create";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};campaign.read=function(a){try{var b="read";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};campaign.update=function(a){try{var b="update";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};campaign.remove=function(a){try{var b="delete";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};campaign.find=function(a){try{var b="find";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};campaign.count=function(a){try{var b="count";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};campaign.execute=function(a){try{var b="execute";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};campaign.doActions=function(a){try{var b="doActions";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};campaign.getHistory=function(a){try{var b="getHistory";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}}
// WorkFlow Module //
var workflow=new Boxcite;workflow.prefix="mq.boxcite.workflow.";workflow.createTransaction=function(a){try{var b="createTransaction";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};workflow.updateTransaction=function(a){try{var b="updateTransaction";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};workflow.readTransaction=function(a){try{var b="readTransaction";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};workflow.findTransaction=function(a){try{var b="findTransaction";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};workflow.count=function(a){try{var b="countTransaction";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};workflow.deleteTransaction=function(a){try{var b="deleteTransaction";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}}
// Message Module //
var message=new Boxcite;message.prefix="mq.boxcite.message.";message.find=function(a){try{var b="find";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};message.count=function(a){try{var b="count";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};message.read=function(a){try{var b="read";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};message.update=function(a){try{var b="update";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};message.remove=function(a){try{var b="delete";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}}
// Report Module //
var report=new Boxcite;report.prefix="mq.boxcite.report.";report.getReport=function(a){try{var b="getReport";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};report.export=function(a){try{var b="export";response=this.sendRequest(b,a);return response}catch(c){c="Error : "+c;throw c}}
