/*
 * Boxcite.JS : the Boxcite-library for the frontend development
 *
 * @copyright mQuotient Solutions Limited
 * @developer Soumya Deb [DebWebDev]
 *
 */

(function(a){function b(a,b,c){this.data={};this.prefix="";if(typeof a!=="undefined"&&a.length>0){this.URL="http://"+a;if(typeof b!=="undefined"&&b.length>0){this.URL+=":"+b}if(typeof c!=="undefined"&&c.length>0){this.URL+=c}}else this.URL="http://localhost/xmlrpc/";this.getCookie=function(a){var b,c,d,e="";var f=document.cookie.split(";");var g=f.length;if(g<=0&&f[0]!=""){for(b=0;b<g;b++){c=f[b].substr(0,f[b].indexOf("="));d=f[b].substr(f[b].indexOf("=")+1);c=c.replace(/^\s+|\s+$/g,"");if(c==a){e=unescape(d);return e}}}return e};this.setCookie=function(a,b,c,d,e){var f=new Date;f.setDate(f.getDate()+c);var g=escape(b)+(c==null?"":";expires="+f.toUTCString());g+=d==null?"":"; Domain="+escape(d);g+=e==null?"":"; Path="+escape(e);document.cookie=a+"="+g};this.delCookie=function(a){this.setCookie(a,"",1)};this.loginRequest=function(a,b){try{var c=new xmlrpc_client(this.URL);a=this.prefix+a;e=this.getCookie("sessionid");payLoad=typeof b==="undefined"?this.data:b;if(e!=null){payLoad.sessionID=e}var d=c.mq_send(new xmlrpcmsg(a,new Array(xmlrpc_encode(payLoad))));e=this.getCookie("sessionid");if(e==""){var e=d.cookies();this.setCookie("sessionid",e["sessionid"].value,e["sessionid"].expires)}else alert("Cookie set automatically");d=xmlrpc_decode(d.value());return d}catch(f){f="Failed to initiate sending data - "+f;throw f}};this.logoutRequest=function(a){try{var b=new xmlrpc_client(this.URL);a=this.prefix+a;this.delCookie("sessionid");var c=b.mq_send(new xmlrpcmsg(a,new Array(xmlrpc_encode())));return c}catch(d){d="Failed to initiate sending data - "+d;throw d}}}a.Boxcite=b})(window);var users=new Boxcite;users.prefix="mq.boxcite.user.";users.login=function(a){try{var b="login";response=this.loginRequest(b,a);return response}catch(c){c="Error : "+c;throw c}};users.logout=function(a){try{var b="logout";response=this.logoutRequest(b);return response}catch(c){c="Error : "+c;throw c}}
